sudo: required

language: python

python:
  - "3.4"

services:
  - docker

cache:
  - apt

env:
  - MONGO_IMAGE=mongo:3.2.7 REDIS_IMAGE=redis:latest DOCKER_OPTIONS="-e USE_MONGO_SERVER=1 -e WIDUKIND_MONGODB_URL=mongodb://mongodb/widukind_test --link=mongodb:mongodb -e WIDUKIND_REDIS_URL=redis://redis:6379/0 --link=redis:redis --rm"

before_install:
  - docker pull $MONGO_IMAGE
  - docker pull $REDIS_IMAGE
  - docker run -d --name=mongodb $MONGO_IMAGE mongod --noauth
  - docker run -d --name=redis $REDIS_IMAGE redis-server --appendonly yes
  - docker build -t widukind/api -f DockerfileTests .
  - pip install coveralls

before_script:
  - sleep 15
  - env
  - docker run $DOCKER_OPTIONS widukind/api pip freeze

script:
  - docker run $DOCKER_OPTIONS -e COVERAGE_FILE=/coverage/.coverage -v $PWD/coverage:/coverage widukind/api nosetests --with-coverage -s -v widukind_api
  - docker run $DOCKER_OPTIONS widukind/api flake8 --exit-zero widukind_api

after_script: COVERAGE_FILE=./coverage/.coverage coveralls --verbose

notifications:
  email: true
  on_success: always
  on_failure: always
